export default [
    "Psychological",
    "Martial Arts",
    "Action",
    "Lolicon",
    "Harem",
    "Mecha",
    "Xianxia",
    "Sci-fi",
    "Wuxia",
    "Josei",
    "Slice of Life",
    "Shotacon",
    "Adult",
    "Yuri",
    "Comedy",
    "Mystery",
    "Mature",
    "Ecchi",
    "Sports",
    "Xuanhuan",
    "Seinen",
    "Adventure",
    "Shounen Ai",
    "Horror",
    "Shoujo Ai",
    "Romance",
    "School Life",
    "Yaoi",
    "Shounen",
    "Tragedy",
    "Shoujo",
    "Drama",
    "Gender Bender",
    "Fantasy",
    "Supernatural",
    "Historical",
    "Smut"
]