export default [
    "Rescue",
    "Outer Space",
    "Antihero Protagonist",
    "Inheritance",
    "Hard-Working Protagonist",
    "Adapted From Manga",
    "Secret Identity",
    "Forced Into A Relationship",
    "Love At First Sight",
    "Magical Space",
    "Cautious Protagonist",
    "Blind Protagonist",
    "Half-human Protagonist",
    "Adapted From Manhua",
    "Childish Protagonist",
    "Modern Day",
    "Imperial Harem",
    "Familiars",
    "Sister Complex",
    "Based On A Movie",
    "Androids",
    "Handsome Male Lead",
    "Artifact Crafting",
    "Episodic",
    "Shota",
    "Multiple Reincarnated Individuals",
    "Different Social Status",
    "Seven Deadly Sins",
    "Affair",
    "Evolution",
    "Amnesia",
    "Necromancer",
    "Interconnected Storylines",
    "Assassins",
    "System Administrator",
    "Misandry",
    "Reincarnated as a Monster",
    "Stalkers",
    "Previous Life Talent",
    "Prostitutes",
    "Matriarchy",
    "Divine Protection",
    "Soldiers",
    "Living Abroad",
    "Cooking",
    "Organ Transplant",
    "Writers",
    "Alchemy",
    "Swordsman",
    "Dungeon Master",
    "Child Abuse",
    "Technological Gap",
    "Pollution",
    "Heterochromia",
    "Apathetic Protagonist",
    "Male Protagonist",
    "Skill Books",
    "Rape",
    "Introverted Protagonist",
    "Blood Manipulation",
    "Multiple Pov",
    "Family Conflict",
    "Weak to Strong",
    "Scientists",
    "Gladiators",
    "Guilds",
    "Grave Keepers",
    "Popular Love Interests",
    "Hibernation",
    "Polyandry",
    "Tsundere",
    "Beast Companions",
    "Shounen-Ai Subplot",
    "Time Skip",
    "Sect Development",
    "Magic Beasts",
    "Omegaverse",
    "Blackmail",
    "Amusement Park",
    "Sleeping",
    "Healers",
    "Doting Older Siblings",
    "Poor Protagonist",
    "Female Protagonist",
    "Selfless Protagonist",
    "Based On An Anime",
    "Clingy Lover",
    "Persistent Love Interests",
    "Chuunibyou",
    "Poisons",
    "Low Key Protagonist",
    "Ancient China",
    "Psychopaths",
    "Transported Into A Game World",
    "Loyal Subordinates",
    "Fleet Battles",
    "Valkyrie",
    "Sexual Abuse",
    "Female Master",
    "Detectives",
    "Farming",
    "Spirits",
    "Battle Competition",
    "Corruption",
    "Bickering Couple",
    "Love Rivals",
    "Spoiled Children",
    "Sex Friends",
    "Torture",
    "Special Abilities",
    "Books",
    "Eunuch",
    "Hackers",
    "Lovers Reunited",
    "Pill Concocting",
    "Hot-blooded Protagonist",
    "Time Paradox",
    "Eidetic Memory",
    "Roommates",
    "Guardian Relationship",
    "Poor To Rich",
    "Hypnotism",
    "Enlightenment",
    "Gate To Another World",
    "Prisoner Of War",
    "Businessmen",
    "Unrequited Love",
    "Sudden Wealth",
    "Forced Marriage",
    "Dungeon In Real-World",
    "Orcs",
    "Dragons",
    "Childhood Friends",
    "Demon Lord",
    "Angels",
    "Goddesses",
    "Shameless Protagonist",
    "College/university",
    "Reverse Harem",
    "Award-winning Work",
    "Boss-Subordinate Relationship",
    "Fat To Fit",
    "Samurai",
    "Clan Building",
    "Incubus",
    "Reincarnated Into Another World",
    "Proactive Protagonist",
    "Tentacles",
    "Discrimination",
    "Death",
    "Kidnappings",
    "Appearance Different from Actual Age",
    "Library",
    "Clubs",
    "Game Ranking System",
    "Adapted To Movie",
    "Curious Protagonist",
    "Protagonist Loyal to Love Interest",
    "Blacksmith",
    "Sealed Power",
    "Wishes",
    "Clumsy Love Interests",
    "Male Lead Falls in Love First",
    "Summoning Magic",
    "Depictions Of Cruelty",
    "Cosmic Wars",
    "Resurrection",
    "Sentimental Protagonist",
    "Threesome",
    "Long Separations",
    "Lost Civilizations",
    "Biochip",
    "Otaku",
    "Librarians",
    "Magical Girls",
    "Sudden Strength Gain",
    "Mature Protagonist",
    "Evil Protagonist",
    "Human Experimentation",
    "Past Plays a Big Role",
    "Spatial Manipulation",
    "Orgy",
    "Brainwashing",
    "Cheats",
    "Body Tempering",
    "Misunderstandings",
    "Academy",
    "Nightmares",
    "Multiple Timelines",
    "Ancient Times",
    "Kind Love Interests",
    "Anti-Magic",
    "Philosophical",
    "Part-Time Job",
    "Couple Growth",
    "Marriage of Convenience",
    "Accelerated Growth",
    "Humanoid Protagonist",
    "Loli",
    "Loner Protagonist",
    "Knights",
    "Glasses-wearing Protagonist",
    "Gunfighters",
    "Army Building",
    "Immortals",
    "Royalty",
    "Sex Slaves",
    "Righteous Protagonist",
    "Swords",
    "Student Council",
    "Empires",
    "Onmyouji",
    "Evil Gods",
    "Body-double",
    "Harsh Training",
    "Zombies",
    "Bloodlines",
    "Lawyers",
    "Cute Protagonist",
    "Restaurant",
    "Waiters",
    "Inscriptions",
    "Music",
    "Yandere",
    "Battle Academy",
    "Appearance Changes",
    "Prosthesis",
    "European Ambience",
    "Social Outcasts",
    "Anti-social Protagonist",
    "Late Romance",
    "Fast Cultivation",
    "First Love",
    "Imaginary Friend",
    "Golems",
    "Transported Into Another World",
    "Netori",
    "Hikikomori",
    "Reincarnation",
    "Star Cultivation",
    "Succubus",
    "Ugly To Beautiful",
    "Economics",
    "Heaven",
    "Multiple Transported Individuals",
    "Cultivation",
    "Pilots",
    "Showbiz",
    "Office Romance",
    "Playboys",
    "Servants",
    "Straight Uke",
    "Alternate World",
    "Firearms",
    "Siblings Not Related By Blood",
    "Clones",
    "Voice Actors",
    "Adapted to Drama CD",
    "Religions",
    "Past Trauma",
    "Based On A Video Game",
    "Domestic Affairs",
    "Near-Death Experience",
    "Gangs",
    "Twins",
    "Childhood Promise",
    "Gambling",
    "Demons",
    "Ability Steal",
    "Masochists",
    "Oneshot",
    "Criminals",
    "Animal Rearing",
    "Bride Kidnapping",
    "Terminal Illness",
    "Doting Parents",
    "Engineer",
    "Sharing A Body",
    "Movies",
    "Love Triangles",
    "Cunnilingus",
    "Outdoor Intercourse",
    "Demi-Humans",
    "Disfigurement",
    "Heroes",
    "Saints",
    "Dystopia",
    "Bookworm",
    "Fallen Nobility",
    "Human-Nonhuman Relationship",
    "Coma",
    "Leadership",
    "Cohabitation",
    "Scheming",
    "Fantasy Creatures",
    "Galge",
    "Jealousy",
    "World Travel",
    "Grinding",
    "Antique Shop",
    "Dao Companion",
    "Family Business",
    "Teachers",
    "Multiple Protagonists",
    "Mind Control",
    "Secret Crush",
    "Poetry",
    "Master-Disciple Relationship",
    "Adapted to Manhua",
    "Wealthy Characters",
    "War Records",
    "God Protagonist",
    "Selfish Protagonist",
    "Orphans",
    "Animal Characteristics",
    "Male to Female",
    "Survival",
    "Doctors",
    "Underestimated Protagonist",
    "Hated Protagonist",
    "Crime",
    "Shy Characters",
    "Conditional Power",
    "Shapeshifters",
    "Monster Tamer",
    "Youkai",
    "Beasts",
    "Adapted to Game",
    "Unconditional Love",
    "Exorcism",
    "Shikigami",
    "Slave Harem",
    "Fated Lovers",
    "Straight Seme",
    "Shoujo-Ai Subplot",
    "Legends",
    "Investigations",
    "Pregnancy",
    "Bands",
    "Cute Children",
    "Spirit Users",
    "Dense Protagonist",
    "Cunning Protagonist",
    "Mythology",
    "Family",
    "Time Travel",
    "Transplanted Memories",
    "Age Regression",
    "Hell",
    "Netorare",
    "Lazy Protagonist",
    "Game Elements",
    "Adapted To Manhwa",
    "Senpai-Kouhai Relationship",
    "Stockholm Syndrome",
    "Thriller",
    "Devoted Love Interests",
    "Coming of Age",
    "Hospital",
    "Based On A Visual Novel",
    "Transmigration",
    "Aliens",
    "Saving the World",
    "Manipulative Characters",
    "JSDF",
    "Carefree Protagonist",
    "Half-sister",
    "Cold Love Interests",
    "Helpful Protagonist",
    "Insects",
    "Gods",
    "Dark",
    "Tomboyish Female Lead",
    "Arranged Marriage",
    "Childcare",
    "Male Yandere",
    "Otome Game",
    "Smart Children",
    "Incest",
    "Summoned Hero",
    "Schizophrenia",
    "Mute Character",
    "Cross-dressing",
    "Collection Of Short Stories",
    "Unique Cultivation Technique",
    "Overprotective Siblings",
    "Secretive Protagonist",
    "Lucky Protagonist",
    "Siblings",
    "Skill Creation",
    "Netorase",
    "Mismatched Couple",
    "Sculptors",
    "Easy Going Life",
    "Fantasy World",
    "Romantic Subplot",
    "Politics",
    "Spies",
    "Average-looking Protagonist",
    "Earth Invasion",
    "Mysterious Past",
    "Souls",
    "Ugly Protagonist",
    "Adopted Children",
    "Doting Love Interests",
    "Thieves",
    "Unique Weapons",
    "Seduction",
    "Monster Society",
    "Wizards",
    "Fat Protagonist",
    "Parallel Worlds",
    "Living Alone",
    "Mutations",
    "Friends Become Enemies",
    "Crafting",
    "Quiet Characters",
    "Magic Items",
    "Suicides",
    "Artifacts",
    "Industrialization",
    "Survival Game",
    "Single Parent",
    "Programmer",
    "Slow Romance",
    "Dolls/puppets",
    "Stubborn Protagonist",
    "Breast Fetish",
    "Singers",
    "Reincarnated As An Object",
    "Magical Technology",
    "Handjob",
    "Calm Protagonist",
    "Buddhism",
    "Paizuri",
    "Younger Love Interests",
    "Second Chance",
    "Returning From Another World",
    "Ninjas",
    "Long-distance Relationship",
    "Strong Love Interests",
    "Artificial Intelligence",
    "Transported Modern Structure",
    "Rich To Poor",
    "Autism",
    "Medieval",
    "Glasses-wearing Love Interests",
    "Blind Dates",
    "Futanari",
    "Possessive Characters",
    "Cowardly Protagonist",
    "Childhood Love",
    "Mob Protagonist",
    "Pirates",
    "Adventurers",
    "Salaryman",
    "Enemies Become Lovers",
    "Non-human Protagonist",
    "Famous Parents",
    "Evil Organizations",
    "Sword And Magic",
    "Polygamy",
    "Precognition",
    "Kuudere",
    "Fearless Protagonist",
    "Vocaloid",
    "Prophecies",
    "Genius Protagonist",
    "Language Barrier",
    "Former Hero",
    "Apartment Life",
    "Nobles",
    "Dao Comprehension",
    "Female Dominance",
    "Mystery Solving",
    "Dragon Riders",
    "Arms Dealers",
    "Villainess Noble Girls",
    "Biography",
    "Neet",
    "God-human Relationship",
    "Caring Protagonist",
    "Maids",
    "Business Management",
    "Sexual Cultivation Technique",
    "Ghosts",
    "Awkward Protagonist",
    "Possession",
    "Automatons",
    "Forced Living Arrangements",
    "Adapted To Drama",
    "Emotionally Weak Protagonist",
    "Hidden Abilities",
    "Power Couple",
    "Swordsmanship",
    "Werewolves",
    "Lgbt Parents",
    "Personality Changes",
    "Adapted To Visual Novel",
    "Strength-based Social Hierarchy",
    "Sickly Characters",
    "Phoenixes",
    "Legendary Artifacts",
    "Gore",
    "Money Grubber",
    "Flashbacks",
    "Strategic Battles",
    "Strategist",
    "Master-Servant Relationship",
    "Anal",
    "Cosplay",
    "Voyeurism",
    "World Tree",
    "Dwarfs",
    "Tragic Past",
    "Adapted to Manga",
    "Pragmatic Protagonist",
    "Ruthless Protagonist",
    "Female To Male",
    "Mutated Creatures",
    "Martial Spirits",
    "Subtle Romance",
    "Narcissistic Protagonist",
    "Godly Powers",
    "Abusive Characters",
    "Druids",
    "Confident Protagonist",
    "R-15",
    "Secret Organizations",
    "Kingdoms",
    "Masked Character",
    "Fujoshi",
    "Obsessive Love",
    "Witches",
    "Early Romance",
    "Fanaticism",
    "Sadistic Characters",
    "Polite Protagonist",
    "Charismatic Protagonist",
    "Bodyguards",
    "Racism",
    "Post-apocalyptic",
    "Child Protagonist",
    "Goblins",
    "Nationalism",
    "Slave Protagonist",
    "Apocalypse",
    "Cannibalism",
    "Priestesses",
    "Caste System",
    "Forgetful Protagonist",
    "Fast Learner",
    "Honest Protagonist",
    "Spirit Advisor",
    "Protagonist With Two Bodies",
    "Psychic Powers",
    "Perverted Protagonist",
    "Fanfiction",
    "Mysterious Illness",
    "Futuristic Setting",
    "Protagonist Strong from the Start",
    "Army",
    "Quirky Characters",
    "R-18",
    "Charming Protagonist",
    "Aggressive Characters",
    "Invisibility",
    "Character Growth",
    "Sibling's Care",
    "Acupuncture",
    "Non-humanoid Protagonist",
    "Assassinations",
    "Card Games",
    "Bestiality",
    "Beastkin",
    "Confinement",
    "Human Weapon",
    "Radio Host",
    "Conflicting Loyalties",
    "Debts",
    "Co-Workers",
    "Sentient Objects",
    "Engagement",
    "Parent Complex",
    "Unreliable Narrator",
    "Rape Victim Becomes Lover",
    "Multiple Realms",
    "Multiple Identities",
    "Seeing Things Other Humans Can't",
    "Delusions",
    "Magic",
    "Outcasts",
    "Reporters",
    "Stoic Characters",
    "Reluctant Protagonist",
    "Destiny",
    "Dancers",
    "Time Loop",
    "Serial Killers",
    "Absent Parents",
    "Brotherhood",
    "Rebellion",
    "First-time Intercourse",
    "Brother Complex",
    "Cold Protagonist",
    "Multiple Personalities",
    "Cruel Characters",
    "Marriage",
    "Tribal Society",
    "Bdsm",
    "Swordswoman",
    "Transformation Ability",
    "Editors",
    "Cute Story",
    "Conspiracies",
    "Overpowered Protagonist",
    "Time Manipulation",
    "Crossover",
    "Hiding True Abilities",
    "Merchants",
    "Astrologers",
    "Pacifist Protagonist",
    "Daoism",
    "Fox Spirits",
    "Genetic Modification",
    "Twisted Personality",
    "Parasites",
    "Androgynous Characters",
    "Divination",
    "Sharp-tongued Characters",
    "Slaves",
    "Contracts",
    "Military",
    "All-Girls School",
    "Sibling Rivalry",
    "Classic",
    "Beautiful Female Lead",
    "Murders",
    "Photography",
    "Divorce",
    "Adultery",
    "Artists",
    "Virtual Reality",
    "Sign Language",
    "Hunters",
    "Elves",
    "Wars",
    "Eye Powers",
    "Older Love Interests",
    "Seme Protagonist",
    "Masturbation",
    "Revenge",
    "Dreams",
    "Level System",
    "Younger Sisters",
    "Terrorists",
    "Kingdom Building",
    "Weak Protagonist",
    "Acting",
    "Medical Knowledge",
    "Rivalry",
    "Chefs",
    "Death Of Loved Ones",
    "Black Belly",
    "Dishonest Protagonist",
    "Trickster",
    "Games",
    "Secret Relationship",
    "Curses",
    "Demonic Cultivation",
    "Seven Virtues",
    "Clever Protagonist",
    "Priests",
    "Limited Lifespan",
    "Harem-seeking Protagonist",
    "Pretend Lovers",
    "Inferiority Complex",
    "Butlers",
    "Chat Rooms",
    "Exhibitionism",
    "Disability",
    "Interdimensional Travel",
    "Toys",
    "Reverse Rape",
    "Online Romance",
    "Nurses",
    "Folklore",
    "Adapted to Anime",
    "Pill Based Cultivation",
    "Famous Protagonist",
    "Depression",
    "Hiding True Identity",
    "Skill Assimilation",
    "Jobless Class",
    "Mangaka",
    "Comedic Undertone",
    "Aristocracy",
    "Herbalist",
    "Timid Protagonist",
    "Slow Growth At Start",
    "Mind Break",
    "Spear Wielder",
    "Mysterious Family Background",
    "Modern Knowledge",
    "Secrets",
    "Delinquents",
    "Distrustful Protagonist",
    "Playful Protagonist",
    "Dead Protagonist",
    "Dragon Slayers",
    "Store Owner",
    "Power Struggle",
    "Magic Formations",
    "Phobias",
    "Soul Power",
    "Based On A Song",
    "Mythical Beasts",
    "Elderly Protagonist",
    "Parody",
    "Feng Shui",
    "Monsters",
    "Loneliness",
    "Reincarnated Into A Game World",
    "Based On A Tv Show",
    "Models",
    "Adopted Protagonist",
    "Organized Crime",
    "Familial Love",
    "Drugs",
    "Evil Religions",
    "Betrayal",
    "Genies",
    "Prison",
    "Naive Protagonist",
    "Unique Weapon User",
    "Puppeteers",
    "Dungeon Building",
    "Gamers",
    "Heavenly Tribulation",
    "Fairies",
    "Generals",
    "Fellatio",
    "Trap",
    "Age Progression",
    "Female Lead Falls in Love First",
    "Pets",
    "Lottery",
    "Vampires",
    "Elemental Magic",
    "Pharmacist",
    "Teamwork",
    "MMORPG",
    "Dungeons",
    "Non-linear Storytelling",
    "Fallen Angels",
    "Nudity",
    "Determined Protagonist",
    "Smart Couple",
    "Celebrities",
    "Strong To Stronger",
    "Mercenaries",
    "Archery",
    "Monster Girls",
    "Manly Gay Couple",
    "Identity Crisis",
    "Arrogant Characters",
    "Abandoned Children",
    "Broken Engagement",
    "Short Story",
    "Hard Life",
    "Homunculus",
    "Race Change",
    "Bisexual Protagonist",
    "Bullying",
    "Body Swap",
    "Friendship",
    "Jack Of All Trades",
    "Court Official",
    "Cousins",
    "Unlucky Protagonist",
    "Heartwarming",
    "Enemies Become Allies",
    "Student-Teacher Relationship",
    "Younger Brothers",
    "Complex Family Relationships",
    "Management",
    "Police",
    "Lack Of Common Sense",
    "Genderless Protagonist",
    "Jiangshi",
    "Indecisive Protagonist"
]